server:
  port: 8081

back:
  server:
    uri: http://localhost:8080

spring:
  application:
    name: "studentHostel"

security:
  config:
    signinkey: "student_hostel"
    prefix: "Bearer "
    header: "Authorization"
    authoritieskey: "scopes"
    token:
      validityseconds: 18000
