server:
  port: 8080
spring:
  application:
    name: "studenHostel"
  datasource:
    url: "jdbc:mysql://localhost:3306/student_hostel"
    username: root
    password: rootroot
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
